# Generated by Django 2.0.7 on 2018-08-01 15:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_order_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('CANCEL', 'Cancel')], max_length=7),
        ),
    ]
